### ISSUE TITLE
After converting PC save to Switch, and restoring save via JKSV, save slot is erased.

### ISSUE THREAD

**Issue by DeadExo3** [AsteriskAmpersand/MHST2-Save-Tools#2] opened 2021-07-12 22:12 UTC
Like the title says: I convert a save from PC to Switch, then try to copy it to my switch JKSV folder to restore it, but once I launch the game the slot is erased as if I deleted it. Before copying the save to my SD I make sure the Switch editor can actually read the save, so I’m not sure what I’m doing wrong.

**Comment by AsteriskAmpersand** [comment] 2021-07-13 08:04
The slot has to be in use before for the game to detect it. So save in that particular slot and then replace the relevant slot with the file you are transferring.

**Comment by DeadExo3** [comment] 2021-07-13 12:54
> The slot has to be in use before for the game to detect it. So save in that particular slot and then replace the relevant slot with the file you are transferring.

It doesn't make sense then that my original Slot 1 save on my Switch gets erased completely when I try to bring in the converted PC save. When I back up my saves with JKSV it gives me a folder with the 3 save slots, autosave, and system file. When I copy the converted slot 1 PC save, it's overwriting the slot 1 Switch save. Then I restore it using JKSV.

When I back up my Switch save I have the autosave, slot 1, and slot 2. But only slot 1 is getting erased.

**Comment by DeadExo3** [comment] 2021-07-13 13:14
Just for clarification:

First are my PC saves
Second, are my original Switch saves
The third is after I convert the PC slot1 save and restore it to replace the Switch Slot1 save.

![PC saves](https://user-images.githubusercontent.com/87282869/125457723-35e798c5-aab7-45ca-aa7d-93a5290573ac.JPG)
![Original Switch Save](https://user-images.githubusercontent.com/87282869/125457760-545b08a9-f469-4afb-ae31-339a5cf3f84a.jpg)
![After Restoring Slot 1 with Converted PC Save](https://user-images.githubusercontent.com/87282869/125457775-25472809-d761-4212-928e-05226939f847.jpg)

**Comment by DeadExo3** [comment] 2021-07-13 13:57
I converted another PC save, slot2 this time. I only used the .sav_nsw to make sure the save was converted. It opens in the save editor and reads normally. I also know before restoring it to the Switch I need to make it .sav to match the other files. I have attached the converted file here to see if maybe you see an issue I'm not able to communicate.


[mhr_slot_2.zip](https://github.com/AsteriskAmpersand/MHST2-Save-Tools/files/6809314/mhr_slot_2.zip)

**Comment by DeadExo3** [comment] 2021-07-13 15:02
I have to ask if you tested a PC save that was converted to a Switch save being restored using a save manager like Neumann, EdiZon, or JKSV, and then appearing and able to load on the Switch version of MHS2. 

Because while the PC saves I converted to Switch saves are able to be opened in the [MHS2 save editor](https://github.com/turtle-insect/MonsterHunterStories2) like a regular Switch save can, I am unable to get those saves restored to my Switch to be used in the Switch version of the game. My version is a **Nintendo Shop digital copy** if that matters.

**Comment by DeadExo3** [comment] 2021-07-13 15:54
I'm discussing things with other people, they think it might be since the Rise save Kamura outfit doesn't exist on PC, it may be causing issues with Switch.

**Comment by AsteriskAmpersand** [comment] 2021-07-13 16:05
It works with emulators and the save file meets the specifications after bidirectional conversion. I can't really help with external tools, such as whatever you are using to inject the save back into the switch. PC Files still have the Kamura unlocked info they just lack the model. People have already gotten it to work when taking it to an emulator and then back on PC.

I can't help with software I don't write myself. You gottta ask whoever made the tools you are using for save injecting into the switch.

**Comment by iSharingan** [comment] 2021-07-13 16:08
the issue is 100% the Rise save bonus item on Switch. Using a save that HAS DLC to a system that DOESN'T HAVE the same DLC renders the save invalid. I have a plan to figure out what exactly flags the save as invalid, so worst case we should just have to reset specific DLC items and/or a flag or three automatically on save convert.

**Comment by AsteriskAmpersand** [comment] 2021-07-13 17:29
That's already what the tool does. It adds the PC Header and the padding when sent to PC and removes it when going back to switch.

**Comment by iSharingan** [comment] 2021-07-13 17:38
strange that I had to do it manually to get it to work for deadexo, then...

**Comment by DeadExo3** [comment] 2021-07-13 17:50
I will comment that I still can't get the save to function on my Switch.

**Comment by iSharingan** [comment] 2021-07-13 18:04
its possible its the fact the Kamuna Maiden Ena costume is actual DLC on PC and not on Switch - in which case a DLC byte would be involved

**Comment by iSharingan** [comment] 2021-07-13 20:59
Alright. True issue is resolved. The solution is to delete bytes 0xC-0x3B instead of 0x00-0x30. This is in effect the same as adding 0x18 at byte 8 after deleting 0x00-0x30 (the very first byte is occasionally different, but doesn't affect whether the save loads on Switch or not). if the 0x18 is NOT present on a Switch save at 0x08 or if there's data in bytes 0xC-0xF, the game won't load it on Switch.

Screen shots included as an example/to provide detail:
![image](https://user-images.githubusercontent.com/3332462/125524085-4013a356-ff79-4fba-9cfa-08b804040ef4.png)

**Closed** 2021-07-13 21:40 UTC

**Comment by DeadExo3** [comment] 2021-07-13 22:18
> Alright. True issue is resolved. The solution is to delete bytes 0xC-0x3B instead of 0x00-0x30. This is in effect the same as adding 0x18 at byte 8 after deleting 0x00-0x30 (the very first byte is occasionally different, but doesn't affect whether the save loads on Switch or not). if the 0x18 is NOT present on a Switch save at 0x08 or if there's data in bytes 0xC-0xF, the game won't load it on Switch. Deleting 0xC-0x3B is to future-proof the method in case updates change something in the header.
> 
> Screen shots included as an example/to provide detail:
> ![image](https://user-images.githubusercontent.com/3332462/125524085-4013a356-ff79-4fba-9cfa-08b804040ef4.png)

They've done it!
I have my PC progress on my Switch now!

**Comment by iSharingan** [comment] 2021-07-13 22:19
It seems the 01 in the first byte occasionally causes an issue (in which case setting it to 00 fixes it) when moving form PC to Switch. Everything else in my last comment remains correct.

**Comment by OneAutumLeaf1** [comment] 2022-12-12 01:18
Does any have a 100% complete story save file for mhs2 as I haven't been able to progress past lulucion quest due to game crashing
